### ISSUE TITLE
是否还会更新下去

### ISSUE THREAD

**Issue by 492162921** [loremwalker/WebSiteUseful#7]
#### 坚持 or 放弃
这两天被微软刷屏，收购了github．　不知道github的中立性是否还存在
大神你还会坚持下去吗？

**Comment by loremwalker** [comment]
这也是方校长值得庆贺的一件事，gitlab实际上也是azure，我在某群讨论时也了解到，代理azure的也是电信的子公司，还是有些忧虑的，独立运营应该不会，如果是微软参与决策的话，那真就难说了。

坚持，怎么说...，我的重点在修订[fq-book](https://github.com/loremwalker/fq-book)上，网址的更新偶尔看看。如果包青天连这才过百star的repo都要下死手的话，我也没办法，毕竟我身在红朝

**Comment by ImLaoD** [comment]
转移IPFS吧 滑稽.jpg

**Comment by loremwalker** [comment]
也许吧 早些时候用IPNS代替IPFS好很多
