### ISSUE TITLE
个人需要时使用的常用站点中,看电影为本地站点

### ISSUE THREAD

**Issue by AdolphGithub** [loremwalker/WebSiteUseful#8]
#### 说明
个人需要时使用的常用站点中,看电影这项有问题,127.0.0.1是本地的.是否提供一个可以打开或者可以使用的站点.
`####` 标题
个人在需要时使用的站点有问题
看电影
http://127.0.0.1:43110/1PLAYgDQboKojowD3kwdb3CtWmWaokXvfp/

**Comment by loremwalker** [comment]
@AdolphGithub  没有任何问题，这是零网的站点，[建议你先了解零网以及尝试零网的相关操作](https://loremwalker.github.io/fq-book/#/browse/zeronet)
